#!/bin/bash

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg IMAGE_NAME=$IMAGE_NAME \
  --build-arg IMAGE_TAG=`git rev-parse --abbrev-ref HEAD` \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  -t $IMAGE_NAME .